dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

install:
  - apt-get install libusb-1.0-0-dev
  - npm install


script:
  - npm run compile
  - npm run test
  
cache:
  directories:
    - node_modules
