dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

install:
  - rm -rf node_modules/
  - npm install
  - npm install -g ganache-cli@6.2.4

before_script:
  - ganache-cli -a 50 --acctKeys './ganache_account_keys.txt' > ganache_cli.log &

script:
  - npm run test

cache:
  directories:
    - node_modules
