dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

install:
  - npm install

before_script:
  - testrpc > testrpc.log &

script:
  - npm run test
  
cache:
  directories:
    - node_modules
