dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

install:
  - npm install
  - npm install -g ganache-cli

before_script:
  - ganache-cli -a 25 > ganache_cli.log &

script:
  - npm run test
  
cache:
  directories:
    - node_modules
