version: '3'
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganachecli
    expose:
      - "8545"
    ports:
      - "8545:8545"
  protocol2test:
    depends_on:
      - ganache
    build:
      context: .
      dockerfile: Dockerfile.test